//@version=4
// **Implementation**
// Linear Regression Band Basic plots the Linear Regression Channel 
// tracing out three curves overlayed accross the chart. The baseline
// is simply a len period linear regression curve while the upper and 
// lower lines are the absolute distances of the largest deviation, over
// the past len periods from the current candle, plus and minus the current 
// linear regression value. 
// **Note** The chart never closes or wicks out of the Linear Regression
// Band

study("Linear Regression Band Basic", "LRBB", overlay=true)
len = input(72, "Slope Length")
src = input(close, "Slope Source")

len2 = input(72, "Deviation Length")
src2 = input(close, "Deviation Source")

calcSlope(src, len) =>
        sumX = 0.0
        sumY = 0.0
        sumXSqr = 0.0
        sumXY = 0.0
        for i = 0 to len - 1
            val = src[i]
            per = i + 1.0
            sumX := sumX + per
            sumY := sumY + val
            sumXSqr := sumXSqr + per * per
            sumXY := sumXY + val * per
        slope = (len * sumXY - sumX * sumY) / (len * sumXSqr - sumX * sumX)
        average = sumY / len
        intercept = average - slope * sumX / len + slope
        [slope, average, intercept]

calcDev(src,  len) =>
    upDev = 0.0
    dnDev = 0.0
    periods = len - 1
    
    for i = 0 to periods
        [s, a, in] = calcSlope(src, len)
        lrcl = s * i + in
        price = high[i] - lrcl[i]
        if (price>upDev)
            upDev := price
    
        price := lrcl[i] - low[i]
        if (price > dnDev)
            dnDev := price
    [upDev, dnDev]

[up, down] = calcDev(src2, len2)

lrc = linreg(src, len, 0)
lrcup = lrc + up
lrcdn = lrc - down

plot(lrc)
plot(lrcup)
plot(lrcdn)